### Jednorodność, czyli sprawdzenie jak bardzo kolejne pomiary na jednym podłożu różnią się od siebie

In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('data/custom/saved_spectra_2.csv')
df.head(5)

,Raman Shift,"2044_D_siarczyn_sodu_5,5mM_9s_1acc_30%_3","2044_D_siarczyn_sodu_5,5mM_9s_1acc_30%_4","2044_G_siarczyn_sodu_5,5mM_9s_1acc_30%","2044_G_siarczyn_sodu_5,5mM_9s_1acc_30%_2","2044_G_siarczyn_sodu_5,5mM_9s_1acc_30%_3","2045_D_siarczyn_sodu_5,5mM_9s_1acc_30%","2045_D_siarczyn_sodu_5,5mM_9s_1acc_30%_2","2045_D_siarczyn_sodu_5,5mM_9s_1acc_30%_3","2045_G_siarczyn_sodu_5,5mM_9s_1acc_30%","2045_G_siarczyn_sodu_5,5mM_9s_1acc_30%_2","2041_D_siarczyn_sodu_5,5mM_9s_1acc_30%","2041_D_siarczyn_sodu_5,5mM_9s_1acc_30%_2","2041_G_siarczyn_sodu_5,5mM_9s_1acc_30%","2041_G_siarczyn_sodu_5,5mM_9s_1acc_30%_2","2044_D_siarczyn_sodu_5,5mM_9s_1acc_30%_2"
0,494.28,24264.0,19202.0,19938.0,21691.0,17971.0,19999.0,19653.0,22272.0,21057.0,22571.0,11389.0,14643.0,19975.0,16390.0,20459.0
1,496.53,23882.0,19303.0,19560.0,21744.0,17940.0,19828.0,19730.0,22601.0,21284.0,22362.0,11137.0,14449.0,19391.0,16042.0,20226.0
2,498.78,23848.0,19179.0,19719.0,21431.0,17981.0,19997.0,19758.0,22588.0,21257.0,22669.0,11350.0,14152.0,19511.0,16249.0,20696.0
3,501.02,23832.0,19126.0,19356.0,21235.0,17633.0,20072.0,19190.0,21916.0,20932.0,22118.0,11000.0,13631.0,19011.0,16213.0,20093.0
4,503.27,23433.0,18699.0,19125.0,21269.0,17303.0,19680.0,19321.0,21714.0,21107.0,22093.0,11147.0,14064.0,18866.0,16238.0,20391.0

In [13]:
df = df.set_index('Raman Shift').T.iloc[:,-10:]

In [14]:
df.head(5)

Raman Shift,1783.78,1785.49,1787.19,1788.90,1790.60,1792.31,1794.01,1795.72,1797.42,1799.12
"2044_D_siarczyn_sodu_5,5mM_9s_1acc_30%_3",3409.0,3534.0,3467.0,3561.0,3535.0,3449.0,3273.0,3547.0,3369.0,3332.0
"2044_D_siarczyn_sodu_5,5mM_9s_1acc_30%_4",3049.0,3094.0,2892.0,2954.0,3019.0,2977.0,3021.0,2989.0,2818.0,2864.0
"2044_G_siarczyn_sodu_5,5mM_9s_1acc_30%",3305.0,3220.0,3105.0,3281.0,3265.0,3295.0,3123.0,3209.0,3171.0,3349.0
"2044_G_siarczyn_sodu_5,5mM_9s_1acc_30%_2",3429.0,3332.0,3437.0,3516.0,3603.0,3557.0,3327.0,3388.0,3343.0,3251.0
"2044_G_siarczyn_sodu_5,5mM_9s_1acc_30%_3",2812.0,2732.0,2835.0,2875.0,2839.0,2852.0,2766.0,2881.0,2716.0,2780.0

In [15]:
num_rows = len(df)
podloze = np.array([0] * (num_rows // 2) + [1] * (num_rows - num_rows // 2))
modyfikacja = np.tile([0, 1], int(len(df) / 2) + 1)[:len(df)]
df['podloze'] = podloze
df['modyfikacja'] = modyfikacja

In [16]:
df.head()

Raman Shift,1783.78,1785.49,1787.19,1788.9,1790.6,1792.31,1794.01,1795.72,1797.42,1799.12,podloze,modyfikacja
"2044_D_siarczyn_sodu_5,5mM_9s_1acc_30%_3",3409.0,3534.0,3467.0,3561.0,3535.0,3449.0,3273.0,3547.0,3369.0,3332.0,0,0
"2044_D_siarczyn_sodu_5,5mM_9s_1acc_30%_4",3049.0,3094.0,2892.0,2954.0,3019.0,2977.0,3021.0,2989.0,2818.0,2864.0,0,1
"2044_G_siarczyn_sodu_5,5mM_9s_1acc_30%",3305.0,3220.0,3105.0,3281.0,3265.0,3295.0,3123.0,3209.0,3171.0,3349.0,0,0
"2044_G_siarczyn_sodu_5,5mM_9s_1acc_30%_2",3429.0,3332.0,3437.0,3516.0,3603.0,3557.0,3327.0,3388.0,3343.0,3251.0,0,1
"2044_G_siarczyn_sodu_5,5mM_9s_1acc_30%_3",2812.0,2732.0,2835.0,2875.0,2839.0,2852.0,2766.0,2881.0,2716.0,2780.0,0,0

Liczymy odchylenie standardowe dla wszystkich pomiarów na danym podłożu. W wyniku tej operacji otrzymujemy odchylenia standardowe dla każdego punktu w obrębie pojedynczego podłoża.

In [23]:
std = df.iloc[:,:].groupby(['modyfikacja', 'podloze']).std()

In [24]:
std

Raman Shift             1783.78     1785.49     1787.19      1788.9  \
modyfikacja podloze
0           0        277.073997  331.720766  261.600204  343.404887
            1        709.955104  783.265387  762.807260  763.661956
1           0        222.036784  249.080977  289.931601  330.092411
            1        731.361060  712.707689  681.287751  718.279658

Raman Shift              1790.6     1792.31     1794.01     1795.72  \
modyfikacja podloze
0           0        360.926932  318.464022  220.957009  301.454668
            1        820.500813  750.850851  683.868896  728.037316
1           0        336.309877  374.709221  252.081997  247.087704
            1        713.493284  770.119201  662.113032  779.297547

Raman Shift             1797.42     1799.12
modyfikacja podloze
0           0        281.511841  290.623898
            1        694.825877  768.797763
1           0        335.001990  257.589467
            1        652.768974  723.698545

Następnie liczymy średnią odchyleń dla wszystkich punktów w ramach jednego podłoża.

In [25]:
n_features = std.shape[1]
std['std_mean'] = std.iloc[:,:n_features].mean(axis=1)

In [26]:
std

Raman Shift             1783.78     1785.49     1787.19      1788.9  \
modyfikacja podloze
0           0        277.073997  331.720766  261.600204  343.404887
            1        709.955104  783.265387  762.807260  763.661956
1           0        222.036784  249.080977  289.931601  330.092411
            1        731.361060  712.707689  681.287751  718.279658

Raman Shift              1790.6     1792.31     1794.01     1795.72  \
modyfikacja podloze
0           0        360.926932  318.464022  220.957009  301.454668
            1        820.500813  750.850851  683.868896  728.037316
1           0        336.309877  374.709221  252.081997  247.087704
            1        713.493284  770.119201  662.113032  779.297547

Raman Shift             1797.42     1799.12    std_mean
modyfikacja podloze
0           0        281.511841  290.623898  298.773822
            1        694.825877  768.797763  746.657122
1           0        335.001990  257.589467  289.392203
            1        652.768974  723.698545  714.512674

Mamy średnie odchylenie dla każdego podłoża bez modyfikacji i z modyfikacją. Możemy teraz policzyć odchylenie/średnią z odchylenia dla wszystkich podłoży z modyfikacją i bez niej. Będzie to ostateczny wynik, który możemy użyć do porówniania między sobą podłoży.